apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: redis.klot.io
spec:
  namespace: redis-klot-io
  description: Redis Server - Kloud of Things I/O
  manifests:
  - path: kubernetes/namespace.yaml
  - path: kubernetes/db.yaml
  settings:
  - name: storage
    description: Where you want Redis to be stored
    node: enabled
