apiVersion: klot.io/v1
kind: App
metadata:
  name: redis.klot.io
  description: Redis Server - Kloud of Things I/O
  version: v0.1
spec:
  namespace: redis-klot-io
  manifests:
  - path: kubernetes/namespace.yaml
  - path: kubernetes/db.yaml
  labels:
  - name: storage
    description: Where you want Redis to be stored
    value: enabled
    master: true
