apiVersion: klot.io/v1
kind: App
metadata:
  name: redis.klot.io
  description: Redis Server - Kloud of Things I/O
spec:
  source:
    site: github.com
    repo: klot-io/redis
  manifests:
  - path: kubernetes/namespace.yaml
  - path: kubernetes/daemon.yaml
  labels:
  - name: storage
    description: Required to place Redis
    value: enabled
    master: true
  settings:
  - name: redis
    version: "5.0.3"
    host: db.redis-klot-io
    port: 6379
