apiVersion: klot.io/v1
kind: App
metadata:
  name: redis.klot.io
  description: Redis Server - Kloud of Things I/O
spec:
  source:
    site: github.com
    repo: klot-io/redis
  namespace: redis-klot-io
  manifests:
  - path: kubernetes/db.yaml
  labels:
  - name: storage
    description: Where you want Redis to be stored
    value: enabled
    master: true
