apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: redis
spec:
  template:
    spec:
      volumes:
      - name: redis
      containers:
      - name: redis
        image: redis-klot-io
        imagePullPolicy: Never
