apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: redis
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      nodeSelector:
        redis.klot.io/storage: enabled
      volumes:
      - name: redis
        hostPath:
          path: /home/pi/storage/redis.klot.io
      containers:
      - name: redis
        image: klotio/redis:0.2
        volumeMounts:
        - name: redis
          mountPath: /data
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: redis
spec:
  selector:
    app: db
  type: ClusterIP
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
